[build]
functions = "functions"
publish = "build"

[[redirects]]
from = "/*"
status = 200
to = "/index.html"

[[headers]]
# Define which paths this specific [[headers]] block will cover.
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
